default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  adapter: postgresql
  username: developer

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  database: health_test
  password: 1234

production:
  <<: *default
  database: health_test_production
  password: 1234
